local keycode_to_string_tbl = {
    [ng.KC_ESCAPE] = '<escape>',
    [ng.KC_ENTER] = '<enter>',
    [ng.KC_TAB] = '<tab>',
    [ng.KC_BACKSPACE] = '<backspace>',
    [ng.KC_INSERT] = '<insert>',
    [ng.KC_DELETE] = '<delete>',
    [ng.KC_RIGHT] = '<right>',
    [ng.KC_LEFT] = '<left>',
    [ng.KC_DOWN] = '<down>',
    [ng.KC_UP] = '<up>',
    [ng.KC_PAGE_UP] = '<page_up>',
    [ng.KC_PAGE_DOWN] = '<page_down>',
    [ng.KC_HOME] = '<home>',
    [ng.KC_END] = '<end>',
    [ng.KC_CAPS_LOCK] = '<caps_lock>',
    [ng.KC_SCROLL_LOCK] = '<scroll_lock>',
    [ng.KC_NUM_LOCK] = '<num_lock>',
    [ng.KC_PRINT_SCREEN] = '<print_screen>',
    [ng.KC_PAUSE] = '<pause>',
    [ng.KC_F1] = '<f1>',
    [ng.KC_F2] = '<f2>',
    [ng.KC_F3] = '<f3>',
    [ng.KC_F4] = '<f4>',
    [ng.KC_F5] = '<f5>',
    [ng.KC_F6] = '<f6>',
    [ng.KC_F7] = '<f7>',
    [ng.KC_F8] = '<f8>',
    [ng.KC_F9] = '<f9>',
    [ng.KC_F10] = '<f10>',
    [ng.KC_F11] = '<f11>',
    [ng.KC_F12] = '<f12>',
    [ng.KC_F13] = '<f13>',
    [ng.KC_F14] = '<f14>',
    [ng.KC_F15] = '<f15>',
    [ng.KC_F16] = '<f16>',
    [ng.KC_F17] = '<f17>',
    [ng.KC_F18] = '<f18>',
    [ng.KC_F19] = '<f19>',
    [ng.KC_F20] = '<f20>',
    [ng.KC_F21] = '<f21>',
    [ng.KC_F22] = '<f22>',
    [ng.KC_F23] = '<f23>',
    [ng.KC_F24] = '<f24>',
    [ng.KC_F25] = '<f25>',
    [ng.KC_KP_0] = '<kp_0>',
    [ng.KC_KP_1] = '<kp_1>',
    [ng.KC_KP_2] = '<kp_2>',
    [ng.KC_KP_3] = '<kp_3>',
    [ng.KC_KP_4] = '<kp_4>',
    [ng.KC_KP_5] = '<kp_5>',
    [ng.KC_KP_6] = '<kp_6>',
    [ng.KC_KP_7] = '<kp_7>',
    [ng.KC_KP_8] = '<kp_8>',
    [ng.KC_KP_9] = '<kp_9>',
    [ng.KC_KP_DECIMAL] = '<kp_decimal>',
    [ng.KC_KP_DIVIDE] = '<kp_divide>',
    [ng.KC_KP_MULTIPLY] = '<kp_multiply>',
    [ng.KC_KP_SUBTRACT] = '<kp_subtract>',
    [ng.KC_KP_ADD] = '<kp_add>',
    [ng.KC_KP_ENTER] = '<kp_enter>',
    [ng.KC_KP_EQUAL] = '<kp_equal>',
    [ng.KC_LEFT_SHIFT] = '<shift>',
    [ng.KC_LEFT_CONTROL] = '<control>',
    [ng.KC_LEFT_ALT] = '<alt>',
    [ng.KC_LEFT_SUPER] = '<super>',
    [ng.KC_RIGHT_SHIFT] = '<shift>',
    [ng.KC_RIGHT_CONTROL] = '<control>',
    [ng.KC_RIGHT_ALT] = '<alt>',
    [ng.KC_RIGHT_SUPER] = '<super>',
    [ng.KC_MENU] = '<menu>'
}
function ng.input_keycode_to_string(key)
    return keycode_to_string_tbl[tonumber(key)] or string.char(ns.input.keycode_to_char(key))
end

local mousecode_to_string_tbl = {
    [ng.MC_1] = '<mouse_1>',
    [ng.MC_2] = '<mouse_2>',
    [ng.MC_3] = '<mouse_3>',
    [ng.MC_4] = '<mouse_4>',
    [ng.MC_5] = '<mouse_5>',
    [ng.MC_6] = '<mouse_6>',
    [ng.MC_7] = '<mouse_7>',
    [ng.MC_8] = '<mouse_8>'
}
function ng.input_mousecode_to_string(mouse)
    return mousecode_to_string_tbl[tonumber(mouse)]
end
